---
# See: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Check for issues with GHA
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  # Check for issues with python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
