---
# See: https://github.com/release-drafter/release-drafter?tab=readme-ov-file
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📚 Documentation"
    label: "docs"
# TODO: consider adding categories for:
#       build ci chore docs feat fix perf refactor revert style test
##
# See: https://github.com/release-drafter/release-drafter?tab=readme-ov-file#autolabeler
autolabeler:
  - label: "docs"
    files:
      - "*.md"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "chore"
    files:
      - "tests/**.py"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'

# See: https://github.com/release-drafter/release-drafter?tab=readme-ov-file#configuration-options
template: |
  ## Changes

  $CHANGES
